### ISSUE TITLE
/lib/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by BlackMoon** [m-lab/prometheus-bigquery-exporter#37] opened 2022-04-20 11:56 UTC
Having 
`/bin/prometheus-bigquery-exporter: symbol lookup error: /lib/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE` issue when try to start exporter locally via Docker

Steps to reproduce:
1. download repo
2. build Docker-image 
`docker build -t bqx-local -f Dockerfile .`

4. run with default arguments

`docker run -p 9348:9348 --rm \           
  -v $HOME/.config/gcloud:/root/.config/gcloud \
  -v $PWD:/queries -it bqx-local \
    -project $GCLOUD_PROJECT \
    -guage-query /queries/example/config/bq_example.sql`

**Comment by stephen-soltesz** [comment] 2022-04-20 12:15
Confirmed.

We should use versioned base images in the Dockerfile. Attempting to migrate to alpine base images did not work due to some dependency on `cgo` within some dependency. This is probably why we base on `busybox:glibc` today. Needs work to identify appropriate versioned glibc images or to eliminate dependency that depends on cgo (which may not be possible - I think that's in the prometheus libs iirc - but may be mistaken).

**Comment by stephen-soltesz** [comment] 2022-04-20 21:49
@BlackMoon Thank you for the original report. We've merged a change that we believe addresses your original report. If it does not, please let us know!

**Closed** 2022-04-20 21:48 UTC
Labels: review/triage
